# Generated by Django 4.1.1 on 2022-12-19 22:55

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ecommerce_app.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("username", models.CharField(default="", max_length=30)),
                ("email", models.EmailField(max_length=100, unique=True)),
                (
                    "first_name",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "family_name",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                ("is_active", models.BooleanField(blank=True, default=True, null=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=13,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9]*$", "only numbers are allowed"
                            )
                        ],
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("VENDOR", "VENDOR"),
                            ("CLIENT", "CLIENT"),
                            ("ADMIN", "ADMIN"),
                        ],
                        default="VENDOR",
                        max_length=8,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "name",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                ("price", models.IntegerField(default=0)),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("SMALL", "S"),
                            ("MEDIUM", "M"),
                            ("LARGE", "L"),
                            ("EXTRA_LARGE", "XL"),
                            ("EXTRA_EXTRA_LARGE", "XXL"),
                        ],
                        default="S",
                        max_length=18,
                    ),
                ),
                (
                    "color",
                    models.CharField(blank=True, default="", max_length=20, null=True),
                ),
                ("quantity", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(2022, 12, 19, 22, 55, 36, 884511),
                        null=True,
                    ),
                ),
                ("weight", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "sku",
                    models.CharField(blank=True, default="", max_length=20, null=True),
                ),
                (
                    "barcode",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "link",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecommerce_app.category",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(2022, 12, 19, 22, 55, 36, 885612),
                        null=True,
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        choices=[
                            ("ONE_MONTH", "ONE_MONTH"),
                            ("TWO_MONTHS", "TWO_MONTHS"),
                            ("THREE_MONTHS", "THREE_MONTHS"),
                        ],
                        default="ONE_MONTH",
                        max_length=15,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(2022, 12, 19, 22, 55, 36, 885668),
                        null=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(2022, 12, 19, 22, 55, 36, 885676),
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("running", "running"),
                            ("expired", "expired"),
                        ],
                        default="expired",
                        max_length=15,
                    ),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "shop_name",
                    models.CharField(blank=True, default="", max_length=20, null=True),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to=ecommerce_app.models.upload_product_image,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecommerce_app.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="product",
            name="shop",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ecommerce_app.shop",
            ),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(
                            2022,
                            12,
                            19,
                            22,
                            55,
                            36,
                            886112,
                            tzinfo=datetime.timezone.utc,
                        ),
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("COMPLETED", "COMPLETED"), ("PENDING", "PENDING")],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("payment_validated", models.BooleanField(default=False)),
                (
                    "client_fullname",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "wilaya",
                    models.CharField(blank=True, default="", max_length=30, null=True),
                ),
                (
                    "client_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=13,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9]*$", "only numbers are allowed"
                            )
                        ],
                    ),
                ),
                (
                    "address",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "payment_amount",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecommerce_app.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
