# Generated by Django 4.1.1 on 2022-09-25 18:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0002_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(2022, 9, 25, 18, 38, 57, 931640),
                        null=True,
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        choices=[
                            ("ONE_MONTH", "ONE_MONTH"),
                            ("TWO_MONTHS", "TWO_MONTHS"),
                            ("THREE_MONTHS", "THREE_MONTHS"),
                        ],
                        default="ONE_MONTH",
                        max_length=15,
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
