# Generated by Django 4.1.1 on 2022-09-26 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0003_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.CharField(
                choices=[
                    ("SMALL", "S"),
                    ("MEDIUM", "M"),
                    ("LARGE", "L"),
                    ("EXTRA_LARGE", "XL"),
                    ("EXTRA_EXTRA_LARGE", "XXL"),
                ],
                default="S",
                max_length=18,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2022, 9, 26, 9, 18, 35, 314575, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
