# Generated by Django 4.1.1 on 2022-09-26 09:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0004_alter_product_size_alter_subscription_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2022, 9, 26, 9, 40, 42, 116012, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(
                            2022, 9, 26, 9, 40, 42, 116468, tzinfo=datetime.timezone.utc
                        ),
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("COMPLETED", "COMPLETED"), ("PENDING", "PENDING")],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("payment_validated", models.BooleanField(default=False)),
                (
                    "product_id",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecommerce_app.product",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
