# Generated by Django 4.1.1 on 2022-09-26 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0005_alter_subscription_created_at_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2022, 9, 26, 9, 45, 18, 534430, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2022, 9, 26, 9, 45, 18, 533853, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
