# Generated by Django 4.1.1 on 2022-10-03 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0008_alter_order_created_at_alter_subscription_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2022, 10, 3, 15, 14, 24, 452274, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2022, 10, 3, 15, 14, 24, 451866, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
