# Generated by Django 4.1.1 on 2022-10-04 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ecommerce_app",
            "0011_alter_order_created_at_alter_subscription_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2022, 10, 4, 16, 41, 0, 863456, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2022, 10, 4, 16, 41, 0, 863073, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
