# Generated by Django 4.1.1 on 2023-01-02 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0020_subscriptiontype_alter_order_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2023, 1, 2, 21, 17, 10, 130178, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 1, 2, 21, 17, 10, 128349),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 1, 2, 21, 17, 10, 129454),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 1, 2, 21, 17, 10, 129529),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="started_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 1, 2, 21, 17, 10, 129518),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptiontype",
            name="duration",
            field=models.DurationField(
                blank=True, default=datetime.timedelta(days=30), null=True
            ),
        ),
    ]
