# Generated by Django 4.1.1 on 2022-10-17 20:33

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0021_alter_order_created_at_alter_subscription_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="user_id",
        ),
        migrations.AddField(
            model_name="subscription",
            name="is_valid",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="owner",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="phone",
            field=models.CharField(
                blank=True,
                default="",
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]*$", "only numbers are allowed"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2022, 10, 17, 20, 33, 32, 532608, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2022, 10, 17, 20, 33, 32, 532204, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("VENDOR", "VENDOR"),
                    ("CLIENT", "CLIENT"),
                    ("ADMIN", "ADMIN"),
                ],
                default="VENDOR",
                max_length=8,
            ),
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shop_name",
                    models.CharField(blank=True, default="", max_length=20, null=True),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
