# Generated by Django 4.1.1 on 2022-10-17 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ecommerce_app",
            "0022_remove_subscription_user_id_subscription_is_valid_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2022, 10, 17, 20, 35, 31, 122995, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2022, 10, 17, 20, 35, 31, 122597, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
