# Generated by Django 4.1.1 on 2022-10-19 15:03

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ecommerce_app",
            "0042_alter_order_created_at_alter_subscription_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2022, 10, 19, 15, 3, 38, 288902, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2022, 10, 19, 15, 3, 38, 288229, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="phone",
            field=models.CharField(
                blank=True,
                default="",
                max_length=13,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]*$", "only numbers are allowed"
                    )
                ],
            ),
        ),
    ]
