# Generated by Django 4.1.1 on 2022-10-23 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0056_alter_order_created_at_alter_subscription_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="is_valid",
        ),
        migrations.AddField(
            model_name="subscription",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2022, 10, 23, 21, 3, 21, 84061, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="started_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2022, 10, 23, 21, 3, 21, 84050, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2022, 10, 23, 21, 3, 21, 84453, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2022, 10, 23, 21, 3, 21, 83983, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
