# Generated by Django 4.1.1 on 2022-12-14 13:21

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ecommerce_app",
            "0085_alter_order_created_at_alter_product_created_at_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="user_id",
        ),
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="client_fullname",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="client_phone",
            field=models.CharField(
                blank=True,
                default="",
                max_length=13,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]*$", "only numbers are allowed"
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="wilayas",
            field=models.CharField(blank=True, default="", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2022, 12, 14, 13, 21, 10, 764890, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 12, 14, 13, 21, 10, 763165),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 12, 14, 13, 21, 10, 764134),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 12, 14, 13, 21, 10, 764270),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="started_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 12, 14, 13, 21, 10, 764261),
                null=True,
            ),
        ),
    ]
