import { useRouter } from "next/router";
import Head from "next/head";
import { useState, useEffect } from "react";
import axios from "axios";
import CircularProgress from "@mui/material/CircularProgress";
import Box from "@mui/material/Box";
import ProductDetails from "../../components/ProductDetails/ProductDetails";
import styles from "../../styles/ProductDetails.module.css";

export default function Product() {
  const colors = [
    {
      name: "white",
      code: "white",
    },
    {
      name: "black",
      code: "black",
    },
  ];

  const router = useRouter();
  const productId = router?.query?.productId;
  const [loading, setLoading] = useState(true);
  const [product, setProduct] = useState(Object);

  const fetchProduct = async (productId: any) => {
    const endpoint = `http://localhost:8000/client-products/${productId}/`;

    axios
      .get(endpoint)
      .then((res) => {
        console.log("fetched product: ", res?.data);
        setProduct(res?.data);
        setLoading(false);
      })
      .then((err) => {
        console.log("Error while fetching client product: ", err);
      });
  };
  useEffect(() => {
    if (productId != undefined) fetchProduct(productId);
  }, [productId]);

  if (loading)
    return (
      <Box sx={{ display: "flex" }}>
        <CircularProgress />
      </Box>
    );
  else
    return (
      <div className={styles.container}>
        <Head>
          <title>شعاري</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <ProductDetails
            title={product?.name}
            colors={colors}
            description=""
            images={product?.images}
            price={product?.price}
          />
        </main>
      </div>
    );
}
