
import Head from 'next/head'
import ProductDetails from '../../components/ProductDetails/ProductDetails'
import styles from '../../styles/ProductDetails.module.css'

export default function Product() {
    const colors =[
        {
            name:"white",
            code:"white"
        },
        {
            name:"black",
            code:"black"
        }
    ]
  return (
    <div className={styles.container}>
      <Head>
        <title>شعاري</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ProductDetails
            title=""
            colors={colors} 
            description=""
            images={["/tshirt1.jpg","/tshirt1.jpg","/tshirt1.jpg"]}
            price={300}

        />
      </main>
    </div>
  )
}
